### ISSUE TITLE
Why have you commented all the code?

### ISSUE THREAD

**Issue by whitehatdevv** [OvidioSantoro/react-traffic-lights#4]
https://github.com/OvidioSantoro/react-traffic-lights/blob/bf4ec0a3a7ec0c5523bbb4d01c8fc3a28402ab4f/src/js/index.js#L1

Please keep in mind all the rules and mandatories which I have said during the class. As you remember 😁, you mustn't comment all the code, only, you need to comment code which can confuse someone who is working with you. For example, the following instance is obvious you don't need to comment it.

```js 
import Home from '../Home.jsx'
```

Please remove all unnecessary code from your project and send the assignment again via BreathCode.

**Comment by OvidioSantoro** [comment]
Removed all unnecessary comments. I tend to comment on all the code when, as you said, is unnecessary for any developer with minimum experience. This will be the way of action from now on.
