### ISSUE TITLE
What are the meaning of Home Component?

### ISSUE THREAD

**Issue by whitehatdevv** [OvidioSantoro/react-traffic-lights#5]
https://github.com/OvidioSantoro/react-traffic-lights/blob/bf4ec0a3a7ec0c5523bbb4d01c8fc3a28402ab4f/src/js/component/home.jsx#L1

All of us have created a `Home` component which haven't any functionality, this hasn't any sense. One more layer, one more problem. Keep in mind to make your code as simple as possible, you need to focus on understand which pieces are needed to accomplish the project requirements. 

**Think on that:** Why do you need a home component which functionality is create an instance of another component?

I know, you are overwhelmed, don't worry about that, only think that `Home` component don't have any sense here, it's one more layer that can complicate your code and get less memory free. All pieces are allocated in memory, don't forget.

Task: You must complete all the requirements (which you should think) to satisfy all the issues I have just exposed here. NOT FORGETTING, I'm here to help you, if you have any question or any doubt about this comment please don't hesitate in contact me, I really appreciate when you ask me something, it's my real work 😄

**Comment by OvidioSantoro** [comment]
Home component deleted. This was a legacy component inherited from the boilerplate provided. In this case, as you said, it's completely meaningless and serves no purpose, so the code now calls the main component directly.
